/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LogicButton {
        "value": any;
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLLogicButtonElement extends Components.LogicButton, HTMLStencilElement {
    }
    var HTMLLogicButtonElement: {
        prototype: HTMLLogicButtonElement;
        new (): HTMLLogicButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "logic-button": HTMLLogicButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface LogicButton {
        "value"?: any;
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "logic-button": LogicButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "logic-button": LocalJSX.LogicButton & JSXBase.HTMLAttributes<HTMLLogicButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
